//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dominion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Cards&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Witch&lt;/Name&gt;
        ///    &lt;Gained&gt;Curse&lt;/Gained&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Embargo&lt;/Name&gt;
        ///    &lt;Gained&gt;Curse&lt;/Gained&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Sea Hag&lt;/Name&gt;
        ///    &lt;Gained&gt;Curse&lt;/Gained&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Mountebank&lt;/Name&gt;
        ///    &lt;Gained&gt;Curse&lt;/Gained&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Hermit&lt;/Name&gt;
        ///    &lt;Gained&gt;Madman&lt;/Gained&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Urchin&lt;/Name&gt;
        ///    &lt;Gained&gt;Mercenary&lt;/Gained&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string additionalCards {
            get {
                return ResourceManager.GetString("additionalCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Cards&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Copper&lt;/Name&gt;
        ///    &lt;Cost&gt;0&lt;/Cost&gt;
        ///    &lt;Type&gt;Treasure&lt;/Type&gt;
        ///    &lt;Description&gt;+1 Coins&lt;/Description&gt;
        ///    &lt;Set&gt;Common&lt;/Set&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Silver&lt;/Name&gt;
        ///    &lt;Cost&gt;3&lt;/Cost&gt;
        ///    &lt;Type&gt;Treasure&lt;/Type&gt;
        ///    &lt;Description&gt;+2 Coins&lt;/Description&gt;
        ///    &lt;Set&gt;Common&lt;/Set&gt;
        ///  &lt;/Card&gt;
        ///  &lt;Card&gt;
        ///    &lt;Name&gt;Gold&lt;/Name&gt;
        ///    &lt;Cost&gt;5&lt;/Cost&gt;
        ///    &lt;Type&gt;Treasure&lt;/Type&gt;
        ///    &lt;Description&gt;+3 Coins&lt;/Description&gt;
        ///    &lt;Set&gt;Common&lt;/Set&gt;
        ///  &lt;/C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DCG_Credits {
            get {
                object obj = ResourceManager.GetObject("DCG_Credits", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DCG_Credits_Link {
            get {
                object obj = ResourceManager.GetObject("DCG_Credits_Link", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
